@section("base-template")
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        @yield("useBootstrapCss")
        <title><?= $viewVariables->exampleName ?> | Peppers PHP Framework</title>
        <link rel="icon" href="/images/favicon-32x32.ico">
        <style type="text/css">
            header {
                margin: 1.3rem 0;
                padding: 0.3rem;
            }
        </style>
    </head>
    <body>
        @yield("pageHeader")
        <main>
            @yield("content")
        </main>
        @yield("pageFooter")
        @yield("useBootstrapJs")
    </body>
</html>
@endsection

@section("pageHeader")
<div class="container">
    <div class="row">
        <div class="col">
            <header class="col">
                <img class="img-thumbnail float-start" src="/images/peppers-128x128.png" width="75px" height="75px"/>
                <span class="fs-1 ms-2"><?= $viewVariables->exampleName ?> in <span style="color: green">Peppers</span> PHP Framework</span>
            </header>
        </div>
    </div>
</div>
@endsection

@section("pageFooter")
<footer class="mt-5 py-3 bg-light">
    <div class="container">
        <a href="/"><span class="text-muted">Home</span></a>&nbsp;|&nbsp;<span>Server time: <?= date('Y-m-d H:i:s') ?></span>
    </div>
</footer>
@endsection

@section("useBootstrapCss")
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
@endsection

@section("useBootstrapJs")
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
@endsection