@extends("examples.templates.base-template")
@use("examples.forms.generic-error-list")

@section("content")
<div class="container">
    <div class="row">
        <div class="col">
            <p>Feel free to check all available validators in <code>Peppers\Helpers\DataValidation</code> namespace to learn how to write your own validation classes.<p>
            <hr>
        </div>
    </div>
    <form action="<?= $viewVariables->action ?>" method="POST">
        <div class="row">
            <div class="col-6">
                <label class="form-label" for="name">Name</label>
                <input class="form-control" type="text" id="name" name="name">
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                <label class="form-label" for="name">Email</label>
                <input class="form-control" type="text" id="email" name="email">
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                <label class="form-label" for="name">Telephone</label>
                <input class="form-control" type="text" id="phone" name="phone">
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                <hr>
                <button class="btn btn-primary btn-lg" type="submit">Submit</button>
            </div>
        </div>
    </form>
</div>
<?php if ($viewVariables->has('name')) { ?>
    <div class="container">
        <div class="row">
            <div class="col-6">
                <p>You submitted:</p>
                <ul>
                    <li>Name: <?= $viewVariables->name ?></li>
                    <li>Email: <?= $viewVariables->email ?></li>
                    <li>Telephone: <?= $viewVariables->phone ?></li>
                </ul>
            </div>
        </div>
    </div>
<?php } ?>
@yield("generic-error-list")
@endsection