@extends("examples.templates.base-template")

@section("content")
<div class="container">
    <div class="row fs-4">
        <div class="col">
            <p>This content comes from file: <code>&lt;DocumentRoot&gt;/App/Views/examples/view/extended.phtml</code></p>
            <p>The HTML document/template where this view is used comes from file - <code>&lt;DocumentRoot&gt;/App/Views/examples/template.phtml</code> - which this view extends. That is the top document (read about it below).</p>
        </div>
        @yield("mainContent")
    </div>
</div>
@endsection
