@extends("examples.templates.base-template")
@use("examples.forms.generic-error-list")

@section("content")
<div class="container">
    <form action="<?= $viewVariables->action ?>" method="POST" enctype="multipart/form-data">
        <div class="row">
            <div class="col-6">
                <label class="form-label" for="name">File</label>
                <input class="form-control" type="file" name="file">
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                <hr>
                <button class="btn btn-primary btn-lg" type="submit">Submit</button>
            </div>
        </div
    </form>
</div>
<?php if ($viewVariables->has('file')) { ?>
    <div class="container">
        <div class="row">
            <div class="col-6">
                <p>You submitted:</p>
                <ul>
                    <li>File: <?= $viewVariables->file ?></li>
                    <li>MIME type: <?= $viewVariables->mimetype ?></li>
                </ul>
            </div>
        </div>
    </div>
<?php } ?>
@yield("generic-error-list")
@endsection